/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    workspaces: Workspace;
    media: Media;
    worlds: World;
    locations: Location;
    characters: Character;
    'rule-sets': RuleSet;
    'rule-modules': RuleModule;
    'rule-definitions': RuleDefinition;
    'rule-generation-policies': RuleGenerationPolicy;
    'rule-releases': RuleRelease;
    'rule-migrations': RuleMigration;
    'rule-documents': RuleDocument;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    workspaces: WorkspacesSelect<false> | WorkspacesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    worlds: WorldsSelect<false> | WorldsSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    characters: CharactersSelect<false> | CharactersSelect<true>;
    'rule-sets': RuleSetsSelect<false> | RuleSetsSelect<true>;
    'rule-modules': RuleModulesSelect<false> | RuleModulesSelect<true>;
    'rule-definitions': RuleDefinitionsSelect<false> | RuleDefinitionsSelect<true>;
    'rule-generation-policies': RuleGenerationPoliciesSelect<false> | RuleGenerationPoliciesSelect<true>;
    'rule-releases': RuleReleasesSelect<false> | RuleReleasesSelect<true>;
    'rule-migrations': RuleMigrationsSelect<false> | RuleMigrationsSelect<true>;
    'rule-documents': RuleDocumentsSelect<false> | RuleDocumentsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  auth0Subject: string;
  role: 'admin' | 'author';
  workspace?: (number | null) | Workspace;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workspaces".
 */
export interface Workspace {
  id: number;
  name: string;
  externalId: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  workspace: number | Workspace;
  altText: string;
  purpose: 'world-map' | 'location-map' | 'portrait' | 'token' | 'handout' | 'reference';
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  generation?: {
    provider?: string | null;
    model?: string | null;
    promptHash?: string | null;
    correlationId?: string | null;
  };
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "worlds".
 */
export interface World {
  id: number;
  workspace: number | Workspace;
  externalId: string;
  title: string;
  summary: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  featuredMedia?: (number | null) | Media;
  locations?: (number | Location)[] | null;
  characters?: (number | Character)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  workspace: number | Workspace;
  world: number | World;
  title: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  map?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characters".
 */
export interface Character {
  id: number;
  workspace: number | Workspace;
  world: number | World;
  location: number | Location;
  name: string;
  biography: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  portrait?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rule-sets".
 */
export interface RuleSet {
  id: number;
  workspace: number | Workspace;
  externalId: string;
  name: string;
  slug: string;
  summary: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  lifecycle: 'active' | 'deprecated' | 'retired';
  engineFeatureLevel: string;
  dashboard?: {
    icon?: (number | null) | Media;
    accentColor?: string | null;
    featured?: boolean | null;
  };
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rule-modules".
 */
export interface RuleModule {
  id: number;
  workspace: number | Workspace;
  ruleSet: number | RuleSet;
  externalId: string;
  namespace: string;
  name: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  sortOrder: number;
  requiredEngineFeatureLevel: string;
  dependencies:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  exports:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rule-definitions".
 */
export interface RuleDefinition {
  id: number;
  workspace: number | Workspace;
  ruleSet: number | RuleSet;
  module: number | RuleModule;
  externalId: string;
  definitionType:
    | 'entity-type'
    | 'trait'
    | 'field'
    | 'derived-value'
    | 'modifier'
    | 'check'
    | 'resource'
    | 'catalog'
    | 'template'
    | 'operation'
    | 'effect'
    | 'event'
    | 'constraint'
    | 'presentation'
    | 'fixture';
  name: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  schemaVersion: number;
  visibility: 'exported' | 'private';
  body:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  presentation?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  clonedFrom?: (number | null) | RuleDefinition;
  provenance?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rule-generation-policies".
 */
export interface RuleGenerationPolicy {
  id: number;
  workspace: number | Workspace;
  ruleSet: number | RuleSet;
  module?: (number | null) | RuleModule;
  externalId: string;
  name: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  capabilities:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  artifactKinds:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  prohibitions:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  policy:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  schemaVersion: number;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rule-releases".
 */
export interface RuleRelease {
  id: number;
  workspace: number | Workspace;
  ruleSet: number | RuleSet;
  externalId: string;
  version: string;
  contentHash: string;
  engineCompatibility:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  dependencyLock:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  manifest:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  sourceSnapshot:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  publishedBy: number | User;
  publishedAt: string;
  releaseNotes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  lifecycle: 'published' | 'deprecated' | 'retired';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rule-migrations".
 */
export interface RuleMigration {
  id: number;
  workspace: number | Workspace;
  ruleSet: number | RuleSet;
  externalId: string;
  name: string;
  sourceRelease: number | RuleRelease;
  targetRelease: number | RuleRelease;
  transformations:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  rehearsal?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  reversibility: 'reversible' | 'checkpoint-only' | 'irreversible';
  schemaVersion: number;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rule-documents".
 */
export interface RuleDocument {
  id: number;
  workspace: number | Workspace;
  ruleSet: number | RuleSet;
  module?: (number | null) | RuleModule;
  externalId: string;
  title: string;
  kind: 'guide' | 'example' | 'reference' | 'changelog';
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  sortOrder: number;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'workspaces';
        value: number | Workspace;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'worlds';
        value: number | World;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'characters';
        value: number | Character;
      } | null)
    | ({
        relationTo: 'rule-sets';
        value: number | RuleSet;
      } | null)
    | ({
        relationTo: 'rule-modules';
        value: number | RuleModule;
      } | null)
    | ({
        relationTo: 'rule-definitions';
        value: number | RuleDefinition;
      } | null)
    | ({
        relationTo: 'rule-generation-policies';
        value: number | RuleGenerationPolicy;
      } | null)
    | ({
        relationTo: 'rule-releases';
        value: number | RuleRelease;
      } | null)
    | ({
        relationTo: 'rule-migrations';
        value: number | RuleMigration;
      } | null)
    | ({
        relationTo: 'rule-documents';
        value: number | RuleDocument;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  auth0Subject?: T;
  role?: T;
  workspace?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workspaces_select".
 */
export interface WorkspacesSelect<T extends boolean = true> {
  name?: T;
  externalId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  workspace?: T;
  altText?: T;
  purpose?: T;
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  generation?:
    | T
    | {
        provider?: T;
        model?: T;
        promptHash?: T;
        correlationId?: T;
      };
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "worlds_select".
 */
export interface WorldsSelect<T extends boolean = true> {
  workspace?: T;
  externalId?: T;
  title?: T;
  summary?: T;
  body?: T;
  featuredMedia?: T;
  locations?: T;
  characters?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  workspace?: T;
  world?: T;
  title?: T;
  description?: T;
  map?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characters_select".
 */
export interface CharactersSelect<T extends boolean = true> {
  workspace?: T;
  world?: T;
  location?: T;
  name?: T;
  biography?: T;
  portrait?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rule-sets_select".
 */
export interface RuleSetsSelect<T extends boolean = true> {
  workspace?: T;
  externalId?: T;
  name?: T;
  slug?: T;
  summary?: T;
  description?: T;
  lifecycle?: T;
  engineFeatureLevel?: T;
  dashboard?:
    | T
    | {
        icon?: T;
        accentColor?: T;
        featured?: T;
      };
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rule-modules_select".
 */
export interface RuleModulesSelect<T extends boolean = true> {
  workspace?: T;
  ruleSet?: T;
  externalId?: T;
  namespace?: T;
  name?: T;
  description?: T;
  sortOrder?: T;
  requiredEngineFeatureLevel?: T;
  dependencies?: T;
  exports?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rule-definitions_select".
 */
export interface RuleDefinitionsSelect<T extends boolean = true> {
  workspace?: T;
  ruleSet?: T;
  module?: T;
  externalId?: T;
  definitionType?: T;
  name?: T;
  description?: T;
  schemaVersion?: T;
  visibility?: T;
  body?: T;
  presentation?: T;
  clonedFrom?: T;
  provenance?: T;
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rule-generation-policies_select".
 */
export interface RuleGenerationPoliciesSelect<T extends boolean = true> {
  workspace?: T;
  ruleSet?: T;
  module?: T;
  externalId?: T;
  name?: T;
  description?: T;
  capabilities?: T;
  artifactKinds?: T;
  prohibitions?: T;
  policy?: T;
  schemaVersion?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rule-releases_select".
 */
export interface RuleReleasesSelect<T extends boolean = true> {
  workspace?: T;
  ruleSet?: T;
  externalId?: T;
  version?: T;
  contentHash?: T;
  engineCompatibility?: T;
  dependencyLock?: T;
  manifest?: T;
  sourceSnapshot?: T;
  publishedBy?: T;
  publishedAt?: T;
  releaseNotes?: T;
  lifecycle?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rule-migrations_select".
 */
export interface RuleMigrationsSelect<T extends boolean = true> {
  workspace?: T;
  ruleSet?: T;
  externalId?: T;
  name?: T;
  sourceRelease?: T;
  targetRelease?: T;
  transformations?: T;
  rehearsal?: T;
  reversibility?: T;
  schemaVersion?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rule-documents_select".
 */
export interface RuleDocumentsSelect<T extends boolean = true> {
  workspace?: T;
  ruleSet?: T;
  module?: T;
  externalId?: T;
  title?: T;
  kind?: T;
  body?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}