/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  jsonb,
  boolean,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
export const enum_users_role = pgEnum("enum_users_role", ["admin", "author"]);
export const enum_media_purpose = pgEnum("enum_media_purpose", [
  "world-map",
  "location-map",
  "portrait",
  "token",
  "handout",
  "reference",
]);
export const enum_worlds_status = pgEnum("enum_worlds_status", [
  "draft",
  "published",
]);
export const enum__worlds_v_version_status = pgEnum(
  "enum__worlds_v_version_status",
  ["draft", "published"],
);

export const users_sessions = pgTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = pgTable(
  "users",
  {
    id: serial("id").primaryKey(),
    auth0Subject: varchar("auth0_subject").notNull(),
    role: enum_users_role("role").notNull().default("author"),
    workspace: integer("workspace_id").references(() => workspaces.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    uniqueIndex("users_auth0_subject_idx").on(columns.auth0Subject),
    index("users_workspace_idx").on(columns.workspace),
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const workspaces = pgTable(
  "workspaces",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    externalId: varchar("external_id").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("workspaces_external_id_idx").on(columns.externalId),
    index("workspaces_updated_at_idx").on(columns.updatedAt),
    index("workspaces_created_at_idx").on(columns.createdAt),
  ],
);

export const media_tags = pgTable(
  "media_tags",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    value: varchar("value").notNull(),
  },
  (columns) => [
    index("media_tags_order_idx").on(columns._order),
    index("media_tags_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [media.id],
      name: "media_tags_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const media = pgTable(
  "media",
  {
    id: serial("id").primaryKey(),
    workspace: integer("workspace_id")
      .notNull()
      .references(() => workspaces.id, {
        onDelete: "set null",
      }),
    altText: varchar("alt_text").notNull(),
    purpose: enum_media_purpose("purpose").notNull(),
    generation_provider: varchar("generation_provider"),
    generation_model: varchar("generation_model"),
    generation_promptHash: varchar("generation_prompt_hash"),
    generation_correlationId: varchar("generation_correlation_id"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
  },
  (columns) => [
    index("media_workspace_idx").on(columns.workspace),
    index("media_generation_generation_prompt_hash_idx").on(
      columns.generation_promptHash,
    ),
    index("media_generation_generation_correlation_id_idx").on(
      columns.generation_correlationId,
    ),
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
  ],
);

export const worlds = pgTable(
  "worlds",
  {
    id: serial("id").primaryKey(),
    workspace: integer("workspace_id").references(() => workspaces.id, {
      onDelete: "set null",
    }),
    externalId: varchar("external_id"),
    title: varchar("title"),
    summary: varchar("summary"),
    body: jsonb("body"),
    featuredMedia: integer("featured_media_id").references(() => media.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    _status: enum_worlds_status("_status").default("draft"),
  },
  (columns) => [
    index("worlds_workspace_idx").on(columns.workspace),
    uniqueIndex("worlds_external_id_idx").on(columns.externalId),
    index("worlds_featured_media_idx").on(columns.featuredMedia),
    index("worlds_updated_at_idx").on(columns.updatedAt),
    index("worlds_created_at_idx").on(columns.createdAt),
    index("worlds__status_idx").on(columns._status),
  ],
);

export const worlds_rels = pgTable(
  "worlds_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    locationsID: integer("locations_id"),
    charactersID: integer("characters_id"),
  },
  (columns) => [
    index("worlds_rels_order_idx").on(columns.order),
    index("worlds_rels_parent_idx").on(columns.parent),
    index("worlds_rels_path_idx").on(columns.path),
    index("worlds_rels_locations_id_idx").on(columns.locationsID),
    index("worlds_rels_characters_id_idx").on(columns.charactersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [worlds.id],
      name: "worlds_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["locationsID"]],
      foreignColumns: [locations.id],
      name: "worlds_rels_locations_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["charactersID"]],
      foreignColumns: [characters.id],
      name: "worlds_rels_characters_fk",
    }).onDelete("cascade"),
  ],
);

export const _worlds_v = pgTable(
  "_worlds_v",
  {
    id: serial("id").primaryKey(),
    parent: integer("parent_id").references(() => worlds.id, {
      onDelete: "set null",
    }),
    version_workspace: integer("version_workspace_id").references(
      () => workspaces.id,
      {
        onDelete: "set null",
      },
    ),
    version_externalId: varchar("version_external_id"),
    version_title: varchar("version_title"),
    version_summary: varchar("version_summary"),
    version_body: jsonb("version_body"),
    version_featuredMedia: integer("version_featured_media_id").references(
      () => media.id,
      {
        onDelete: "set null",
      },
    ),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__worlds_v_version_status("version__status").default("draft"),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    latest: boolean("latest"),
  },
  (columns) => [
    index("_worlds_v_parent_idx").on(columns.parent),
    index("_worlds_v_version_version_workspace_idx").on(
      columns.version_workspace,
    ),
    index("_worlds_v_version_version_external_id_idx").on(
      columns.version_externalId,
    ),
    index("_worlds_v_version_version_featured_media_idx").on(
      columns.version_featuredMedia,
    ),
    index("_worlds_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_worlds_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_worlds_v_version_version__status_idx").on(columns.version__status),
    index("_worlds_v_created_at_idx").on(columns.createdAt),
    index("_worlds_v_updated_at_idx").on(columns.updatedAt),
    index("_worlds_v_latest_idx").on(columns.latest),
  ],
);

export const _worlds_v_rels = pgTable(
  "_worlds_v_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    locationsID: integer("locations_id"),
    charactersID: integer("characters_id"),
  },
  (columns) => [
    index("_worlds_v_rels_order_idx").on(columns.order),
    index("_worlds_v_rels_parent_idx").on(columns.parent),
    index("_worlds_v_rels_path_idx").on(columns.path),
    index("_worlds_v_rels_locations_id_idx").on(columns.locationsID),
    index("_worlds_v_rels_characters_id_idx").on(columns.charactersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [_worlds_v.id],
      name: "_worlds_v_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["locationsID"]],
      foreignColumns: [locations.id],
      name: "_worlds_v_rels_locations_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["charactersID"]],
      foreignColumns: [characters.id],
      name: "_worlds_v_rels_characters_fk",
    }).onDelete("cascade"),
  ],
);

export const locations = pgTable(
  "locations",
  {
    id: serial("id").primaryKey(),
    workspace: integer("workspace_id")
      .notNull()
      .references(() => workspaces.id, {
        onDelete: "set null",
      }),
    world: integer("world_id")
      .notNull()
      .references(() => worlds.id, {
        onDelete: "set null",
      }),
    title: varchar("title").notNull(),
    description: jsonb("description").notNull(),
    map: integer("map_id").references(() => media.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("locations_workspace_idx").on(columns.workspace),
    index("locations_world_idx").on(columns.world),
    index("locations_map_idx").on(columns.map),
    index("locations_updated_at_idx").on(columns.updatedAt),
    index("locations_created_at_idx").on(columns.createdAt),
  ],
);

export const characters = pgTable(
  "characters",
  {
    id: serial("id").primaryKey(),
    workspace: integer("workspace_id")
      .notNull()
      .references(() => workspaces.id, {
        onDelete: "set null",
      }),
    world: integer("world_id")
      .notNull()
      .references(() => worlds.id, {
        onDelete: "set null",
      }),
    location: integer("location_id")
      .notNull()
      .references(() => locations.id, {
        onDelete: "set null",
      }),
    name: varchar("name").notNull(),
    biography: jsonb("biography").notNull(),
    portrait: integer("portrait_id").references(() => media.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("characters_workspace_idx").on(columns.workspace),
    index("characters_world_idx").on(columns.world),
    index("characters_location_idx").on(columns.location),
    index("characters_portrait_idx").on(columns.portrait),
    index("characters_updated_at_idx").on(columns.updatedAt),
    index("characters_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_kv = pgTable(
  "payload_kv",
  {
    id: serial("id").primaryKey(),
    key: varchar("key").notNull(),
    data: jsonb("data").notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
    workspacesID: integer("workspaces_id"),
    mediaID: integer("media_id"),
    worldsID: integer("worlds_id"),
    locationsID: integer("locations_id"),
    charactersID: integer("characters_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    index("payload_locked_documents_rels_workspaces_id_idx").on(
      columns.workspacesID,
    ),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    index("payload_locked_documents_rels_worlds_id_idx").on(columns.worldsID),
    index("payload_locked_documents_rels_locations_id_idx").on(
      columns.locationsID,
    ),
    index("payload_locked_documents_rels_characters_id_idx").on(
      columns.charactersID,
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["workspacesID"]],
      foreignColumns: [workspaces.id],
      name: "payload_locked_documents_rels_workspaces_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["worldsID"]],
      foreignColumns: [worlds.id],
      name: "payload_locked_documents_rels_worlds_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["locationsID"]],
      foreignColumns: [locations.id],
      name: "payload_locked_documents_rels_locations_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["charactersID"]],
      foreignColumns: [characters.id],
      name: "payload_locked_documents_rels_characters_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ one, many }) => ({
  workspace: one(workspaces, {
    fields: [users.workspace],
    references: [workspaces.id],
    relationName: "workspace",
  }),
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_workspaces = relations(workspaces, () => ({}));
export const relations_media_tags = relations(media_tags, ({ one }) => ({
  _parentID: one(media, {
    fields: [media_tags._parentID],
    references: [media.id],
    relationName: "tags",
  }),
}));
export const relations_media = relations(media, ({ one, many }) => ({
  workspace: one(workspaces, {
    fields: [media.workspace],
    references: [workspaces.id],
    relationName: "workspace",
  }),
  tags: many(media_tags, {
    relationName: "tags",
  }),
}));
export const relations_worlds_rels = relations(worlds_rels, ({ one }) => ({
  parent: one(worlds, {
    fields: [worlds_rels.parent],
    references: [worlds.id],
    relationName: "_rels",
  }),
  locationsID: one(locations, {
    fields: [worlds_rels.locationsID],
    references: [locations.id],
    relationName: "locations",
  }),
  charactersID: one(characters, {
    fields: [worlds_rels.charactersID],
    references: [characters.id],
    relationName: "characters",
  }),
}));
export const relations_worlds = relations(worlds, ({ one, many }) => ({
  workspace: one(workspaces, {
    fields: [worlds.workspace],
    references: [workspaces.id],
    relationName: "workspace",
  }),
  featuredMedia: one(media, {
    fields: [worlds.featuredMedia],
    references: [media.id],
    relationName: "featuredMedia",
  }),
  _rels: many(worlds_rels, {
    relationName: "_rels",
  }),
}));
export const relations__worlds_v_rels = relations(
  _worlds_v_rels,
  ({ one }) => ({
    parent: one(_worlds_v, {
      fields: [_worlds_v_rels.parent],
      references: [_worlds_v.id],
      relationName: "_rels",
    }),
    locationsID: one(locations, {
      fields: [_worlds_v_rels.locationsID],
      references: [locations.id],
      relationName: "locations",
    }),
    charactersID: one(characters, {
      fields: [_worlds_v_rels.charactersID],
      references: [characters.id],
      relationName: "characters",
    }),
  }),
);
export const relations__worlds_v = relations(_worlds_v, ({ one, many }) => ({
  parent: one(worlds, {
    fields: [_worlds_v.parent],
    references: [worlds.id],
    relationName: "parent",
  }),
  version_workspace: one(workspaces, {
    fields: [_worlds_v.version_workspace],
    references: [workspaces.id],
    relationName: "version_workspace",
  }),
  version_featuredMedia: one(media, {
    fields: [_worlds_v.version_featuredMedia],
    references: [media.id],
    relationName: "version_featuredMedia",
  }),
  _rels: many(_worlds_v_rels, {
    relationName: "_rels",
  }),
}));
export const relations_locations = relations(locations, ({ one }) => ({
  workspace: one(workspaces, {
    fields: [locations.workspace],
    references: [workspaces.id],
    relationName: "workspace",
  }),
  world: one(worlds, {
    fields: [locations.world],
    references: [worlds.id],
    relationName: "world",
  }),
  map: one(media, {
    fields: [locations.map],
    references: [media.id],
    relationName: "map",
  }),
}));
export const relations_characters = relations(characters, ({ one }) => ({
  workspace: one(workspaces, {
    fields: [characters.workspace],
    references: [workspaces.id],
    relationName: "workspace",
  }),
  world: one(worlds, {
    fields: [characters.world],
    references: [worlds.id],
    relationName: "world",
  }),
  location: one(locations, {
    fields: [characters.location],
    references: [locations.id],
    relationName: "location",
  }),
  portrait: one(media, {
    fields: [characters.portrait],
    references: [media.id],
    relationName: "portrait",
  }),
}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    workspacesID: one(workspaces, {
      fields: [payload_locked_documents_rels.workspacesID],
      references: [workspaces.id],
      relationName: "workspaces",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    worldsID: one(worlds, {
      fields: [payload_locked_documents_rels.worldsID],
      references: [worlds.id],
      relationName: "worlds",
    }),
    locationsID: one(locations, {
      fields: [payload_locked_documents_rels.locationsID],
      references: [locations.id],
      relationName: "locations",
    }),
    charactersID: one(characters, {
      fields: [payload_locked_documents_rels.charactersID],
      references: [characters.id],
      relationName: "characters",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);

type DatabaseSchema = {
  enum_users_role: typeof enum_users_role;
  enum_media_purpose: typeof enum_media_purpose;
  enum_worlds_status: typeof enum_worlds_status;
  enum__worlds_v_version_status: typeof enum__worlds_v_version_status;
  users_sessions: typeof users_sessions;
  users: typeof users;
  workspaces: typeof workspaces;
  media_tags: typeof media_tags;
  media: typeof media;
  worlds: typeof worlds;
  worlds_rels: typeof worlds_rels;
  _worlds_v: typeof _worlds_v;
  _worlds_v_rels: typeof _worlds_v_rels;
  locations: typeof locations;
  characters: typeof characters;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_workspaces: typeof relations_workspaces;
  relations_media_tags: typeof relations_media_tags;
  relations_media: typeof relations_media;
  relations_worlds_rels: typeof relations_worlds_rels;
  relations_worlds: typeof relations_worlds;
  relations__worlds_v_rels: typeof relations__worlds_v_rels;
  relations__worlds_v: typeof relations__worlds_v;
  relations_locations: typeof relations_locations;
  relations_characters: typeof relations_characters;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
